# Generated by Django 6.0.7 on 2026-07-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(blank=True, max_length=100)),
                ('especialidad', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.PositiveIntegerField()),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(max_length=30)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.barbero')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.servicio')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('barbero', 'fecha', 'hora'), name='unique_barbero_fecha_hora_activa')],
            },
        ),
    ]
