# Generated by Django 6.0.7 on 2026-07-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_disponibilidadbarbero'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='es_combo',
            field=models.BooleanField(default=False),
        ),
    ]
