# Generated by Django 6.0.7 on 2026-08-15 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_servicio_es_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reserva',
            name='token_confirmacion',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
